//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class HexTile : MonoBehaviour
	{
		public GameObject destructibleHexTile;
		public List<Building> buildings = new List<Building>();
		private Color startColor;
		public int hexID = -1;

		void Start(){
			GameObject parentGrid = GameObject.Find ("Grid");
			transform.parent = parentGrid.transform;
		}

		void Update(){

		}

		void OnMouseOver(){
			//transform.localPosition += transform.forward * 0.1f;
			Debug.Log (hexID);

		}

		void OnMouseDown(){
			Debug.Log ("click");

			//destroyTile();

		}

		public void destroyTile(){
			Destroy(gameObject);
			Instantiate (destructibleHexTile, transform.position, transform.rotation);

		}

		void OnMouseEnter(){
			startColor = gameObject.GetComponent<Renderer> ().material.color;
			gameObject.GetComponent<Renderer> ().material.color = Color.yellow;
		}

		void OnMouseExit(){
			gameObject.GetComponent<Renderer> ().material.color = startColor;
		}

	}
}

