//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class HexTile : MonoBehaviour
	{
//		public float elevation = 0;
//		public float colorChangeDuration = 5;
//		public float colorChangeSmoothness = 0.02f;
//		public Color currentColor = Color.white;
//		public Color [] colors;
		public GameObject destructibleHexTile;
		List<Building> buildings = new List<Building>();
		public int hexID = -1;

		void Start(){
			GameObject parentGrid = GameObject.Find ("Grid");
			transform.parent = parentGrid.transform;
//			parentGrid.transform.parent = transform;
//			StartCoroutine("LerpColor");
		}

		void Update(){

		}

//		IEnumerator LerpColor(){
//			float learpProgress = 0;
//			float increment = colorChangeSmoothness / colorChangeDuration;
//
//			while (learpProgress < 1) {
//				currentColor = Color.Lerp (colors[0], colors[1], learpProgress);
//				learpProgress += increment;
//				yield return new WaitForSeconds(colorChangeSmoothness);
//			}
//			return true;
//		}

		void OnMouseOver(){
			//transform.localPosition += transform.forward * 0.1f;
			Debug.Log (hexID);

		}
//		}
//
//		void OnMouseOut(){
//			Vector3 newPosition = new Vector3 (0, 2, 0);
//			transform.position -= newPosition;
//		}
//
		void OnMouseDown(){
			Debug.Log ("click");
			destroyTile();

		}

		public void destroyTile(){
			Destroy(gameObject);
			Instantiate (destructibleHexTile, transform.position, transform.rotation);

		}

	}
}

